CREATE SCHEMA IF NOT EXISTS prevoz
    AUTHORIZATION postgres;
CREATE TABLE prevoz.user
(
    user_id bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);
